# Generated by Django 4.2.6 on 2023-10-22 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricaoProduto', models.CharField(max_length=255)),
                ('trocaTemporaria', models.BooleanField(default=False)),
                ('tempo', models.BigIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SituacaoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SituacaoProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menssagem', models.CharField(max_length=255)),
                ('descricaoProduto', models.CharField(max_length=255)),
                ('trocaTemporaria', models.BooleanField(default=False)),
                ('tempo', models.BigIntegerField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.categoria')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.post')),
                ('proponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.user')),
                ('situacaoPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.situacaopost')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='situacaoPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.situacaopost'),
        ),
        migrations.AddField(
            model_name='post',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.user'),
        ),
        migrations.CreateModel(
            name='InteresseTrocaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.categoria')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.post')),
            ],
        ),
        migrations.CreateModel(
            name='FotoProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='propostas_images')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.proposta')),
            ],
        ),
        migrations.CreateModel(
            name='FotoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='posts_images')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.post')),
            ],
        ),
    ]
