# Generated by Django 4.2.6 on 2023-10-22 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_post_situacaopost_situacaoproposta_proposta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='situacaopost',
            old_name='nome',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='situacaoproposta',
            old_name='nome',
            new_name='descricao',
        ),
        migrations.AlterField(
            model_name='post',
            name='situacaoPost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plataforma.situacaopost'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='situacaoPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.situacaoproposta'),
        ),
    ]
