# Generated by Django 4.2.6 on 2023-10-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_post_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tempo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
